name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  uv-example:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
